# src/tainacan_prep.py

import os
import requests
import pandas as pd
from config import (
    TARGET_VALUES,
    LABEL_SEPARATOR,
    DB_KEY_PARAMETER,
    STATUS_PRIVATE_PARAMETER,
    STATUS_PUBLIC_PARAMETER,
    TEXT_PARAMETER,
    NUMERIC_PARAMETER,
    RELATIONSHIP_PARAMETER,
    OUTPUT_PUBLISH
)


def download_images(data):
    ids = data[TARGET_VALUES[1][0]]
    verso_urls = data[TARGET_VALUES[25][0]].tolist()
    recto_urls = data[TARGET_VALUES[26][0]].tolist()
    img_dir = os.path.join('data','img')
    recto_dir = os.path.join('data','img', 'recto')
    verso_dir = os.path.join('data','img', 'verso') 
    if not os.path.exists(img_dir):
        os.makedirs(img_dir)
    if not os.path.exists(recto_dir):
        os.makedirs(recto_dir)
        for i, url in enumerate(recto_urls):
            if url:
                img_data = requests.get(url).content
                with open(f'{recto_dir}/{ids[i]}-r.jpg', 'wb') as handler:
                    handler.write(img_data)
    if not os.path.exists(verso_dir):
        os.makedirs(verso_dir)
        for i, url in enumerate(verso_urls):
            if url:
                img_data = requests.get(url).content
                with open(f'{verso_dir}/{ids[i]}-v.jpg', 'wb') as handler:
                    handler.write(img_data)
    return


def data_prep(data):
    """
    """
    df = pd.read_csv(data)
    df["special_document"] = "file:disegni/" + df[TARGET_VALUES[1][0]].astype(str) + "-v.jpg"
    df["special_attachments"] = "disegni/" + df[TARGET_VALUES[1][0]].astype(str) + "-v.jpg; disegni/" + df[TARGET_VALUES[1][0]].astype(str) + "-r.jpg"
    df_2 = df.rename(columns={
        TARGET_VALUES[1][0]: LABEL_SEPARATOR.join([TARGET_VALUES[1][1],TEXT_PARAMETER,STATUS_PRIVATE_PARAMETER]),
        TARGET_VALUES[2][0]: LABEL_SEPARATOR.join([TARGET_VALUES[2][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[3][0]: LABEL_SEPARATOR.join([TARGET_VALUES[3][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[4][0]: LABEL_SEPARATOR.join([TARGET_VALUES[4][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[5][0]: LABEL_SEPARATOR.join([TARGET_VALUES[5][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[6][0]: LABEL_SEPARATOR.join([TARGET_VALUES[6][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[7][0]: LABEL_SEPARATOR.join([TARGET_VALUES[7][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[8][0]: LABEL_SEPARATOR.join([TARGET_VALUES[8][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[9][0]: LABEL_SEPARATOR.join([TARGET_VALUES[9][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[10][0]: LABEL_SEPARATOR.join([TARGET_VALUES[10][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[11][0]: LABEL_SEPARATOR.join([TARGET_VALUES[11][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[12][0]: LABEL_SEPARATOR.join([TARGET_VALUES[12][1],NUMERIC_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[13][0]: LABEL_SEPARATOR.join([TARGET_VALUES[13][1],NUMERIC_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[14][0]: LABEL_SEPARATOR.join([TARGET_VALUES[14][1],TEXT_PARAMETER,STATUS_PRIVATE_PARAMETER]),
        TARGET_VALUES[15][0]: LABEL_SEPARATOR.join([TARGET_VALUES[15][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[16][0]: LABEL_SEPARATOR.join([TARGET_VALUES[16][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[17][0]: LABEL_SEPARATOR.join([TARGET_VALUES[17][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[18][0]: LABEL_SEPARATOR.join([TARGET_VALUES[18][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[19][0]: LABEL_SEPARATOR.join([TARGET_VALUES[19][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[20][0]: LABEL_SEPARATOR.join([TARGET_VALUES[20][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[21][0]: LABEL_SEPARATOR.join([TARGET_VALUES[21][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[22][0]: LABEL_SEPARATOR.join([TARGET_VALUES[22][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[23][0]: LABEL_SEPARATOR.join([TARGET_VALUES[23][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[24][0]: LABEL_SEPARATOR.join([TARGET_VALUES[24][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[25][0]: LABEL_SEPARATOR.join([TARGET_VALUES[25][1],TEXT_PARAMETER,STATUS_PRIVATE_PARAMETER]),
        TARGET_VALUES[26][0]: LABEL_SEPARATOR.join([TARGET_VALUES[26][1],TEXT_PARAMETER,STATUS_PRIVATE_PARAMETER]),
        TARGET_VALUES[27][0]: LABEL_SEPARATOR.join([TARGET_VALUES[27][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[28][0]: LABEL_SEPARATOR.join([TARGET_VALUES[28][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[29][0]: LABEL_SEPARATOR.join([TARGET_VALUES[29][1],TEXT_PARAMETER,STATUS_PRIVATE_PARAMETER]),
        TARGET_VALUES[30][0]: LABEL_SEPARATOR.join([TARGET_VALUES[30][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[31][0]: LABEL_SEPARATOR.join([TARGET_VALUES[31][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[32][0]: LABEL_SEPARATOR.join([TARGET_VALUES[32][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
        TARGET_VALUES[33][0]: LABEL_SEPARATOR.join([TARGET_VALUES[33][1],TEXT_PARAMETER,STATUS_PUBLIC_PARAMETER]),
    })
    return df_2.to_csv(OUTPUT_PUBLISH, index=False)